### ISSUE TITLE
Not working for tf2/Insurgency

### ISSUE THREAD

**Issue by Orinion** [CallumCVM/ValveGen#3]
Error message: "Unhandled exception at BLABLABLA (ValveGen.dll) in hl2.exe: 0xC0000005: Access violation reading location 0x00000001."
Error is in line 73. (m_pVarName\* is 0x1)

**Comment by Orinion** [comment]
simple
`((DWORD)prop->m_pDataTable->m_pProps->m_pVarName) >0x1`
check fixes the issue

**Comment by CallumCVM** [comment]
Appreciate the fix but that doesn't address the actual issue. I suspect its
pointer sharing.

Callum MacGregor
CVM Software Solutions

t:   +44 (0)113 256 6017
m: +44 (0)7912 942 073
e:  info@cvm-solutions.co.uk
