### ISSUE TITLE
Can't seem to get it working with mod for hl2

### ISSUE THREAD

**Issue by bypasser105103** [CallumCVM/ValveGen#6]
I have a problem with injecting compiled .dll
*1) Compiled solution in VS2017 (in v140) as (x86 .dll);
*2) Opened the mod on my (x64) system;
*3) Used Cheat Engine 6.7 to inject in into (Source 2007-based) mod in a run-time;
*4) It said "DLL Injected" or something like that;
*5) No dump created anywhere... (Edited after clarification)

Can you help me?

**Comment by CallumCVM** [comment]
This isn't a cheat or something that contains a user interface. It is a
utility for dumping an SDK.


Callum MacGregor
CVM Software Solutions




t:   +44 (0)113 250 5115
m: +44 (0)7912 942 073
e:  info@cvm-solutions.co.uk

**Comment by bypasser105103** [comment]
Thanks for fast response and some clarifications about how it should work, maybe I didn't read main page on UnkCh very carefully.

But what I get is that I load it up and it either doesnt create dump file or I cant find it.
I attach it directly into source 2007 mod's exe hl in a runtime and cant get to understand how it works.
